[tool.poetry]
name = "datadog-logger"
version = "1.0.0"
description = "Python logging handler for DataDog events"
authors = ["uStudio Developers <dev@ustudio.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "datadog_logger"}]

[tool.poetry.dependencies]
python = "^3.9"
datadog = "^0.45.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
flake8 = "^6.0.0"
mypy = "^1.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
