version: 2
jobs:
  test-py39:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Save Python Version
          command: |
            python --version > pythonversion

      - restore_cache:
          keys:
          - v1-{{ checksum "pythonversion" }}-{{ checksum "dev-requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python -m venv ~/venv
            . ~/venv/bin/activate
            pip install -r dev-requirements.txt
            mkdir -p test-reports

      - save_cache:
          paths:
            - ~/venv
          key: v1-{{ checksum "pythonversion" }}-{{ checksum "dev-requirements.txt" }}

      - run:
          name: run tests
          command: |
            . ~/venv/bin/activate
            pytest --verbose --junit-xml=test-reports/pytest.xml

      - store_artifacts:
          path: test-reports
          destination: test-reports-py39

      - store_test_results:
          path: test-reports

  publish:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python -m venv ~/venv
            . ~/venv/bin/activate
            pip install twine

      - run:
          name: Publish to PyPI
          command: |
            . ~/venv/bin/activate
            ./publish_to_pypi.sh

workflows:
  version: 2
  test-and-publish:
    jobs:
      - test-py39:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - test-py39
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*.*/
            branches:
              ignore: /.*/
          context: org-global
